### ISSUE TITLE
Tubemap Hacking Roadmap

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/MatrixTubeMap#1]
- [x] Grab example data state
- [x] Change substitution text
- [x] Speed up development build / edit cycle
- [x] Introduce "link" mismatch type into code
    - [x] has attr() query: "javascript to execute"
- [x] Trigger JavaScript on link click
- [x] Nodes are transparent
- [x] Verified control over Read ordering
- [x] Verified control over Node ordering

### Bugs to Squash
- [x] Link Position not right on all lines
    * Binary search?
- [x] Collapsing multiple read into one line with gaps
- [x] Two orange reads overlapping - start 0 length 1944

**Comment by josiahseaman** [comment]
## control over Node ordering
* id does not control ordering
* id controls coloring (indirectly) `trackColor = forwardReadColors[track.id % forwardReadColors.length];`
* **Sorting** controlled by order a read is in the list, not id.  There's an auto-densify you need to be cautious of with short reads.
* `finalNodeCoverLength` is misleading.  This is the stop index when it is the same node.  If stop < start, it will still be rendered and possibly quite long.
* editing Node id seems to have no effect now, only Node order in list?
* It's important `finalNodeCoverLength` is not longer than the Node it's in or there is a graphical bug
* Declaration order of Nodes doesn't matter now as long as "tracks" sequence order matches the intended order reads list node names in.

**Comment by josiahseaman** [comment]
![image](https://user-images.githubusercontent.com/2256148/65862102-6cea3080-e365-11e9-8fa0-640fa2c93bb2.png)
finalNodeCoverLength was changed to absolute coordinates inside of one node.  e665f5c979509b846350e5b7dc00b16722f78216

**Comment by josiahseaman** [comment]
![image](https://user-images.githubusercontent.com/2256148/65863139-7a081f00-e367-11e9-84d6-6f3fb56fca43.png)
As a generalization, links tend to apply to a full column.  This makes Erik's connecting lines at the bottom more preferable.

**Comment by josiahseaman** [comment]
Yeast dataset:
![image](https://user-images.githubusercontent.com/2256148/65869630-bf7e1980-e372-11e9-862e-ab808efd6e1d.png)

Error stripes are more prominent.  First priority will be removing those.
DRB1 Errors: Tracks 64 & 107.  Errors come guessing the total length of the Node wrong.  This makes reads whose end is after the node end.  Solution: make the node longer.  This comes from --bins= param in tubeify.

**Comment by josiahseaman** [comment]
![image](https://user-images.githubusercontent.com/2256148/65870796-f81ef280-e374-11e9-9062-9b992d8568a8.png)

![image](https://user-images.githubusercontent.com/2256148/65872139-d6733a80-e377-11e9-86b4-231522964163.png)

This visualization seems pretty good at hilghlighting the sections that are linear, the "hubs" that are irreconcilable snarls, and (when dense) the nodes that are mutually exclusive.
